
<div id="up"><a href="#top" title="To the top"><img src="img/up.png" alt="up" /></a></div><!--/#up--> 
 
<div id="footer">

    <div class="footer-holder">
 
        <div class="footer-frame">
  
            <div class="footer-in">
			
			    <ul id="follow-us">
				    <li><a href="#" title="Follow us on facebook"><img src="../img/fb.png" alt="fb" /></a></li>
					<li><a href="#" title="Follow us on twitter"><img src="../img/tw.png" alt="tw" /></a></li>
					<li>follow us on Facebook and Twitter</li>
                </ul><!--/#follow-us-->
 
                <div id="copyright">
    Copyright &copy; 
    <script language="javascript" type="text/javascript"><!--
    var d = new Date();
    document.write(d.getFullYear() + " - ");
    //--></script> Help and support <a href="mailto:support@sundizer.com" title="Mail to support@sundizer.com">support@sundizer.com</a>
                </div><!--/#copyright-->
				
				<div id="logo-footer">
				    <a href="/" title="Soundizer.com"><img src="img/logo-footer.png" alt="Soundizer.com" /></a>
                </div><!--/#logo-footer-->
 
                <a id="autorlink" href="http://&#x0068;&#x0069;&#x006E;&#x0065;&#x0078;&#x002E;&#x0072;&#x0075;/" title="Powered by - &#x0048;&#x0049;&#x004E;&#x0045;&#x0058;&#x002E;&#x0052;&#x0055; - &#x0068;&#x0069;&#x006E;&#x0065;&#x0078;&#x002E;&#x0072;&#x0075;&#x0040;&#x0067;&#x006D;&#x0061;&#x0069;&#x006C;&#x002E;&#x0063;&#x006F;&#x006D;" target="_blank"><span>Powered by - </span>&#x0048;&#x0049;&#x004E;&#x0045;&#x0058;&#x002E;&#x0052;&#x0055;</a>
            
			</div><!--/.footer-in-->
        
		</div><!--/.footer-frame-->
  
    </div><!--/.footer-holder-->
 
</div><!--/#footer-->