<div id="left">

    <em id="update"><a href="#" title="Update results">Update</a><p>1 000 results found</p><i></i></em>
	
    <form action="" id="accordion">
        <div>
            <h3>Category</h3>
            <div>
			    <a href="#?w=960" rel="popup-category" class="poplight select-category" title="Select Category">Select Category</a>
				<div id="popup-category" class="popup-block">
				    <div class="title">Select category<a href="#" title="Clear category">Clear</a><a href="#" title="Select all">Select all</a></div>
				    <ul>
					    <li><span><input type="checkbox" /></span><label>Ambient [123]</label></li>
						<li><span><input type="checkbox" /></span><label>Children [43]</label></li>
					    <li><span><input type="checkbox" /></span><label>Cinematic [53]</label></li>
						<li><span><input type="checkbox" /></span><label>Classic [85]</label></li>
						<li><span><input type="checkbox" /></span><label>Corporate [21]</label>
				            <ul>
				                <li><span><input type="checkbox" /></span><label>News [2]</label></li>
							    <li><span><input type="checkbox" /></span><label>Tech [256]</label></li>
							    <li><span><input type="checkbox" /></span><label>Matiational [63]</label></li>
				            </ul>
						</li>
						<li><span><input type="checkbox" /></span><label>Country, Western [45]</label></li>
						<li><span><input type="checkbox" /></span><label>Brum & Bass, Breakbeat [532]</label></li>
				    </ul>  
					<p><input type="submit" value="Submit" /></p>
				</div><!--/.popup-block-->
				<p>
				    <div class="instruments">
                            <input id="category" type="text" class="tags" value="+ Ambient [123],+ Children [43],+ Cinematic [53],- Classic [85],+ Corporate [21]" />
                    </div><!--/.instruments-->
                </p>
			</div>
        </div>
		
		<div>
            <h3>Track<a href="#" class="clear" title="Clear selections">Clear</a></h3>
            <div>
			    <strong>Lenght:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
				<strong>BPM:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
			    <p><span><input type="checkbox" /></span><label>Hide if undefined BPM</label></p>
				<p><span><input type="checkbox" /></span><label>Hide if BPM changes</label></p>
				<strong>Rating:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
			    <p><span><input type="checkbox" /></span><label>Hide unrated</label></p>
				<strong>Price:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
				<strong>Sales:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
				<strong>Looped audio:</strong>
				<p><span><input type="checkbox" /></span><label>Show  looped only</label></p>
				<strong>Creation date:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
				
			   
			</div>
        </div>
		
		<div>
            <h3>Instruments<a href="#" class="clear" title="Clear selections">Clear</a></h3>
            <div>
				<a href="#?w=960" rel="popup-instruments" class="poplight select-instruments" title="Select instruments">Select instruments</a>
				<div id="popup-instruments" class="popup-block">
				    <div class="title">Select instruments<a href="#" title="Clear selections">Clear</a><a href="#" title="Select all">Select all</a></div>
				    <ul>
					    <li><span><input type="checkbox" /></span><label>Keyboard [21]</label>
					        <ul>
					            <li><span><input type="checkbox" /></span><label>Piano [2]</label></li>
					            <li><span><input type="checkbox" /></span><label>Electric piano [256]</label></li>
					            <li><span><input type="checkbox" /></span><label>Organ [63]</label></li>
					            <li><span><input type="checkbox" /></span><label>Horpsichord [63]</label></li>
					        </ul>
					    </li>
					    <li><span><input type="checkbox" /></span><label>Guitar [21]</label>
					        <ul>
					            <li><span><input type="checkbox" /></span><label>Accoustic guitar [2]</label></li>
					            <li><span><input type="checkbox" /></span><label>distorted guitar [256]</label></li>
					            <li><span><input type="checkbox" /></span><label>Ukulele [63]</label></li>
					            <li><span><input type="checkbox" /></span><label>Electric guitar [63]</label></li>
					        </ul>
					    </li>
					    <li><span><input type="checkbox" /></span><label>Bass [21]</label>
						    <ul>
						    	<li><span><input type="checkbox" /></span><label>Double bass [2]</label></li>
						    	<li><span><input type="checkbox" /></span><label>Electric bass [256]</label></li>
							</ul>
						</li>
				    </ul>
					<ul>
					    <li><span><input type="checkbox" /></span><label>Keyboard [21]</label>
						    <ul>
							    <li><span><input type="checkbox" /></span><label>Piano [2]</label></li>
								<li><span><input type="checkbox" /></span><label>Electric piano [256]</label></li>
								<li><span><input type="checkbox" /></span><label>Organ [63]</label></li>
								<li><span><input type="checkbox" /></span><label>Horpsichord [63]</label></li>
							</ul>
						</li>
						<li><span><input type="checkbox" /></span><label>Guitar [21]</label>
						    <ul>
							    <li><span><input type="checkbox" /></span><label>Accoustic guitar [2]</label></li>
								<li><span><input type="checkbox" /></span><label>distorted guitar [256]</label></li>
								<li><span><input type="checkbox" /></span><label>Ukulele [63]</label></li>
								<li><span><input type="checkbox" /></span><label>Electric guitar [63]</label></li>
							</ul>
						</li>
						<li><span><input type="checkbox" /></span><label>Bass [21]</label>
						    <ul>
							    <li><span><input type="checkbox" /></span><label>Double bass [2]</label></li>
								<li><span><input type="checkbox" /></span><label>Electric bass [256]</label></li>
							</ul>
						</li>
					    <li><span><input type="checkbox" /></span><label>Keyboard [21]</label>
						    <ul>
							    <li><span><input type="checkbox" /></span><label>Piano [2]</label></li>
								<li><span><input type="checkbox" /></span><label>Electric piano [256]</label></li>
								<li><span><input type="checkbox" /></span><label>Organ [63]</label></li>
								<li><span><input type="checkbox" /></span><label>Horpsichord [63]</label></li>
							</ul>
						</li>
				    </ul>
					<ul>
						<li><span><input type="checkbox" /></span><label>Guitar [21]</label>
						    <ul>
							    <li><span><input type="checkbox" /></span><label>Accoustic guitar [2]</label></li>
								<li><span><input type="checkbox" /></span><label>distorted guitar [256]</label></li>
								<li><span><input type="checkbox" /></span><label>Ukulele [63]</label></li>
								<li><span><input type="checkbox" /></span><label>Electric guitar [63]</label></li>
							</ul>
						</li>
						<li><span><input type="checkbox" /></span><label>Bass [21]</label>
						    <ul>
							    <li><span><input type="checkbox" /></span><label>Double bass [2]</label></li>
								<li><span><input type="checkbox" /></span><label>Electric bass [256]</label></li>
							</ul>
						</li>
					</ul>
					<p><input type="submit" value="Submit" /></p>
				</div><!--/.popup-block-->
				<p>
				    <div class="instruments">
                            <input id="instruments" type="text" class="tags" value="+ percussions [123],+ Ukulele [123],+ Sax [123],- Accordion [123],+ Ellectronic drums [123]" />
                    </div><!--/.instruments-->
                </p>
				<em>Note: Tags defined by autors may or may not corruspond to the instruments played in the tracks</em>
			</div>
        </div>
		
		<div>
            <h3>Mood<a href="#" class="clear" title="Clear selections">Clear</a></h3>
            <div>
			    <p>Mood</p>
			</div>
        </div>
		
		<div>
            <h3>Genre</h3>
            <div>
			    <p>Genre</p>
			</div>
        </div>
		
		<div>
            <h3>Author</h3>
            <div>
			    <strong>Author rating:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
				<p><span><input type="checkbox" /></span><label>Hide unrated</label></p>
				<strong>Author sales:</strong>
				<p><input type="text" value="from" class="left" /><input type="text" value="to" class="right" /></p>
				<p><div class="slider"></div></p>
				<p><span><input type="checkbox" /></span><label>Filter by author Name</label></p>
				<p><input type="text" value="Author Name" /></p>
			</div>
        </div>

    </form><!--/#accordion-->

</div><!--/#left-->